(SELECT * FROM emp ORDER BY empno LIMIT 1)
UNION ALL
(SELECT * FROM emp ORDER BY empno LIMIT 1);

(SELECT DISTINCT sal FROM emp ORDER BY sal DESC LIMIT 1 OFFSET 2)
UNION ALL
(SELECT DISTINCT sal FROM emp ORDER BY sal LIMIT 1 OFFSET 2);
